// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger SignUp YAML
//
//  This is a sign up server.
//  Terms Of Service:
//    http://swagger.io/terms/
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v2
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <apiteam@cisco.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - application/xml
//
// swagger:meta
package restapi
